# Auto-generated by qt-pods @Mo. Feb. 2 06:46:25 2015. Do not edit.
# Include this to your application project file with:
# include(../pods.pri)

INCLUDEPATH += \
	../qt-pods-core \
	../qwaitingspinner 

LIBS += \
	-L../qt-pods-core -lqt-pods-core \
	-L../qwaitingspinner -lqwaitingspinner 

include(qt-pods-core/qt-pods-core.pri)
include(qwaitingspinner/qwaitingspinner.pri)

