# Auto-generated by qt-pods. Do not edit.
# Include this to your application project file with:
# include(../pods.pri)
# This file should be put under version control.

include(qt-pods-core/qt-pods-core.pri)
include(qtirc/qtirc.pri)
include(qtwaitingspinner/qtwaitingspinner.pri)

