# Auto-generated by qt-pods @Di. Feb. 3 09:07:13 2015. Do not edit.
# Include this to your application project file with:
# include(../pods.pri)

INCLUDEPATH += \
	../qt-pods-core \
	../qtwaitingspinner 

LIBS += \
	-L../qt-pods-core -lqt-pods-core \
	-L../qtwaitingspinner -lqtwaitingspinner 

include(qt-pods-core/qt-pods-core.pri)
include(qtwaitingspinner/qtwaitingspinner.pri)

