# Auto-generated by qt-pods. Do not edit.
# Include this to your subdirs project file with:
# include(pods-subdirs.pri)
# This file should be put under version control.

SUBDIRS += \
	qt-pods-core \
	qtirc \
	qtwaitingspinner 

